replicaCount: 1
image:
  repository: ffdl/ibmcloud-object-storage-plugin
  pluginrepository: ffdl/ibmcloud-object-storage-deployer
  Build: v0.1
  pluginBuild: v0.1
  pullPolicy: IfNotPresent
cloud: true
namespace: default
