namespace: default
env: dev
has_static_volumes: true
services:
  expose_node_port: true
docker:
  registry: docker.io
  namespace: ffdl
  image_prefix: ffdl-
  pullPolicy: IfNotPresent
trainer:
  version: v0.1.1
  port: 0
  replicas: 1
  cpus: 100m
  memory: 64Mi
restapi:
  version: v0.1.1
  port: 0
  replicas: 1
  cpus: 50m
  memory: 64Mi
lcm:
  version: v0.1.1
  port: 0
  replicas: 1
  cpus: 100m
  memory: 64Mi
  load_training_data_mem_in_mb: 300
  milli_cpu: 60
  mem_in_mb: 300
  device_plugin: true
  # This will used for "volume.beta.kubernetes.io/storage-class" for the shared volume
  shared_volume_storage_class: ""
trainingdata:
  version: v0.1.1
  port: 0
  replicas: 1
  cpus: 50m
  memory: 64Mi
learner:
  tag: master-97
  docker_namespace: ffdl
  kubeSecret: lcm-secrets
databroker:
  tag: v0.1.1
webui:
  version: v0.1.1
  port: 0
  cpus: 50m
  memory: 64Mi
objectstore:
  type: s3_datastore
  username: test
  password: test
elasticsearch:
  address: http://elasticsearch:9200
  username: test
  password: test
  scheme: http
mongo:
  address: localhost:27017
  username: test
  password: test
etcd:
  address: http://etcd:2379
  username: test
  password: test
  prefix: test
log:
  level: INFO
# Default RSA Creds for Horovod
rsapubkey: "ssh-rsa AAAAB3NhiC1...pubkey.stuff.here...xxxBDmUMAxHiN root@fa485b34526a"
rsaprikey: "-----BEGIN RSA PRIVATE KEY-----
MXXEpHIBAAKCAQEAv...
...private key stuff goes here...
...EKtBsk/BOPhiZFttGs=
-----END RSA PRIVATE KEY-----"
